package ssm.blog.entity;

import org.springframework.stereotype.Component;

@Component
public class TBlogger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogger.id
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogger.username
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogger.password
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogger.nickname
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogger.sign
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogger.imagename
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    private String imagename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogger.profile
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    private String profile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogger.id
     *
     * @return the value of t_blogger.id
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogger.id
     *
     * @param id the value for t_blogger.id
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogger.username
     *
     * @return the value of t_blogger.username
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogger.username
     *
     * @param username the value for t_blogger.username
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogger.password
     *
     * @return the value of t_blogger.password
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogger.password
     *
     * @param password the value for t_blogger.password
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogger.nickname
     *
     * @return the value of t_blogger.nickname
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogger.nickname
     *
     * @param nickname the value for t_blogger.nickname
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogger.sign
     *
     * @return the value of t_blogger.sign
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogger.sign
     *
     * @param sign the value for t_blogger.sign
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogger.imagename
     *
     * @return the value of t_blogger.imagename
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogger.imagename
     *
     * @param imagename the value for t_blogger.imagename
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public void setImagename(String imagename) {
        this.imagename = imagename == null ? null : imagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogger.profile
     *
     * @return the value of t_blogger.profile
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogger.profile
     *
     * @param profile the value for t_blogger.profile
     *
     * @mbg.generated Thu Mar 22 06:59:11 CST 2018
     */
    public void setProfile(String profile) {
        this.profile = profile == null ? null : profile.trim();
    }

	@Override
	public String toString() {
		return "TBlogger [id=" + id + ", username=" + username + ", password=" + password + ", nickname=" + nickname
				+ ", sign=" + sign + ", imagename=" + imagename + ", profile=" + profile + "]";
	}
    
}